### ISSUE TITLE
Unable to install in VS2017, parameter 'Path' because it is null

### ISSUE THREAD

**Issue by ClaudeVernier** [WSDOT-GIS/dms-js#7]
Hello, 
I haven't developped for awhile, used to work with C# 2.0.  I created a new TypeScript project in VS2017, added packages for JSQuery 3.3.1 and jquery.TypeScript.DefinitelyTyped 3.1.2, the project compiles and run.

I tried to install dms-conversion but I am not very confident with that command-line tool: 
```pwsh
PM> install dms-conversion
```

This message appears: 
```pwsh
Join-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\TFS\...\packages\jQuery.3.3.1\tools\install.ps1:3 char:14
+ . (Join-Path $toolsPath common.ps1)
+              ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : 	ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand
No Scripts folder found
```

I tried in several new projects, with different versions of JQuery, I understand this is probably not linked to your component but would you have some time to help me ??

Thank you very much, 
Claude VERNIER

**Comment by JeffJacobson** [comment]
I do all of my JavaScript / TypeScript development with [Visual Studio Code](https://code.visualstudio.com/) (rather than the full [Visual Studio IDE](https://visualstudio.microsoft.com/vs/)) and use npm (which comes with [Node](https://nodejs.org/en/)) to manage the packages.

I don't know anything about that Visual Studio package manager that you are using. I don't know if it works with the *npm* registry, which is the only place this library (*dms-conversion*) is registered.
